AWSTemplateFormatVersion: 2010-09-09
Description: This will create a lambda function and an api event which will trigger it. Also, lambda execution role

Transform: 'AWS::Serverless-2016-10-31'
Resources:
  demofunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: This is just a hello world lambda with api integration
      Handler: lambdademofunction.lambda_handler
      Runtime: python3.7
      CodeUri: './lambdademofunction.py'
      Events:
        demoapi:
            # Define an API Gateway endpoint that responds to HTTP GET at /hello
            Type: Api
            Properties:
              Path: /hello
              Method: GET
      MemorySize: 128
      Timeout: 15
      # Policies:
      #   - AWSLambdaExecute # Managed Policy
      #   - Version: '2012-10-17' # Policy Document
      #     Statement:
      #       - Effect: Allow
      #         Action:
      #           - s3:GetObject
      #           - s3:GetObjectACL
      #         Resource: 'arn:aws:s3::demolalit/*'
      Tags:
        Name: demo
